openapi: 3.1.0
info:
  title: Cyclefi API Specification
  version: 1.0.0
  description: Spesifikasi API Cyclefi
externalDocs:
  description: Postman Documentation
  url: https://documenter.getpostman.com/view/28800996/2sB3BEmpmo

paths:
  /api/register:
    post:
      summary: Registrasi User Baru (Manual)
      description: |
        Endpoint untuk registrasi user secara manual. User akan menerima email berisi kode OTP untuk verifikasi email.
        - Jika email & username sudah terdaftar dan sudah diverifikasi, akan ditolak.
        - Jika email sudah terdaftar tapi belum diverifikasi dan username sama, OTP akan dikirim ulang.
        - Jika username sudah terdaftar, akan ditolak.
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: Username unik untuk user
                email:
                  type: string
                  description: Email user yang valid
                password:
                  type: string
                  description: Password minimal 8 karakter
                confirmPassword:
                  type: string
                  description: Konfirmasi password, harus sama dengan password
              required:
                - username
                - email
                - password
                - confirmPassword
      responses:
        '201':
          description: Registrasi berhasil, OTP dikirim ke email user
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Registration successful. Please check your email for OTP.
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      fullname:
                        type: string
                        example: johndoe
                      username:
                        type: string
                        example: johndoe
                      email:
                        type: string
                        example: johndoe@email.com
                      profile_picture:
                        type: string
                        example: /src/assets/profiles/johndoe.png
        '200':
          description: OTP dikirim ulang ke email user yang belum diverifikasi
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: OTP resent, please check your email
                  data:
                    type: object
                    properties:
                      email:
                        type: string
                        example: johndoe@email.com
        '400':
          description: Validasi gagal atau data sudah terdaftar
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  errors:
                    type: object
                    example:
                      username:
                        - "Username already registered"
                      email:
                        - "Email already registered"
                      password:
                        - "password length must be at least 8 characters long"
                      confirmPassword:
                        - "confirmPassword must be equal with password"

  /api/verify-email:
    post:
      summary: Verifikasi Email User dengan OTP || Resend OTP
      description: |
        Endpoint untuk verifikasi email user setelah registrasi menggunakan kode OTP yang dikirim ke email.
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: Email user yang akan diverifikasi
                otp:
                  type: string
                  description: Kode OTP yang diterima user melalui email
              required:
                - email
                - otp
      responses:
        '200':
          description: Email berhasil diverifikasi
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Email verification successful.
                  data:
                    type: object
                    properties:
                      email:
                        type: string
                        example: johndoe@email.com
                      verified:
                        type: boolean
                        example: true
        '400':
          description: Kode OTP salah atau sudah expired
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  errors:
                    type: string
                    example: OTP code is incorrect or has expired
        '404':
          description: User tidak ditemukan
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  errors:
                    type: string
                    example: User not found

  /api/resend-otp:
    post:
      summary: Kirim Ulang OTP Verifikasi Email
      description: |
        Endpoint untuk mengirim ulang OTP ke email user yang belum diverifikasi.
        - Jika email belum terdaftar, akan ditolak.
        - Jika email sudah terverifikasi, akan ditolak.
        - Jika email belum terverifikasi, OTP baru akan dikirim ke email.
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: Email user yang akan dikirim ulang OTP
              required:
                - email
      responses:
        '200':
          description: OTP berhasil dikirim ulang ke email user
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: OTP resent, please check your email
                  data:
                    type: object
                    properties:
                      email:
                        type: string
                        example: johndoe@email.com
        '400':
          description: Email sudah terverifikasi atau validasi gagal
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  errors:
                    type: string
                    example: Email already registered
        '404':
          description: Email tidak ditemukan
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  errors:
                    type: string
                    example: Email not found

  /api/auth/google:
    get:
      summary: Redirect ke Google OAuth
      description: |
        Endpoint untuk memulai proses login/register dengan Google OAuth. User akan diarahkan ke halaman login Google.
      tags:
        - Auth
      responses:
        '302':
          description: Redirect ke halaman login Google

  /api/auth/google/callback:
    get:
      summary: Callback dari Google OAuth
      description: |
        Endpoint callback setelah user login dengan Google. Jika sukses, user akan otomatis login/register.
        - Jika email sudah ada dan belum verifikasi, akun akan diaktifkan.
        - Jika email sudah ada dan sudah verifikasi, user langsung login.
        - Jika email belum ada, user baru akan dibuat.
      tags:
        - Auth
      responses:
        '201':
          description: Register/login dengan Google berhasil
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Register with Google successful
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      fullname:
                        type: string
                        example: johndoe
                      username:
                        type: string
                        example: johndoe_google
                      email:
                        type: string
                        example: johndoe@email.com
                      profile_picture:
                        type: string
                        example: https://lh3.googleusercontent.com/a/abc123
        '400':
          description: Validasi gagal atau error lain
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  errors:
                    type: string
                    example: Error message















